name: Run NBA Reddit Script Daily

on:
  schedule:
    - cron: "30 6 * * *"  # runs daily at 11:30 PM PT
  workflow_dispatch:       # allows manual runs from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Reddit script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python reddit_api.py -dr 1 -ot worst

